/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myles_NativeStudent */

#ifndef _Included_com_myles_NativeStudent
#define _Included_com_myles_NativeStudent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myles_NativeStudent
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myles_NativeStudent_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_myles_NativeStudent
 * Method:    setName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_myles_NativeStudent_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_myles_NativeStudent
 * Method:    getAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myles_NativeStudent_getAge
  (JNIEnv *, jobject);

/*
 * Class:     com_myles_NativeStudent
 * Method:    setAge
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_myles_NativeStudent_setAge
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
